// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0E9hLYvjvadXMDnqY6HexGZuQITzr0A4',
    appId: '1:696167834323:web:31ada1560d15e53744aa26',
    messagingSenderId: '696167834323',
    projectId: 'notes-flutter-8b72d',
    authDomain: 'notes-flutter-8b72d.firebaseapp.com',
    storageBucket: 'notes-flutter-8b72d.firebasestorage.app',
    measurementId: 'G-29WW8G9BB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArq6-tcZtsoYqKrpCR51J8R3rBbvVLmco',
    appId: '1:696167834323:android:1ff8492702300b4944aa26',
    messagingSenderId: '696167834323',
    projectId: 'notes-flutter-8b72d',
    storageBucket: 'notes-flutter-8b72d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo4dtpH3fxsjLV7TonfSnxAzhBErZilgY',
    appId: '1:696167834323:ios:31c3f2758ba2c88b44aa26',
    messagingSenderId: '696167834323',
    projectId: 'notes-flutter-8b72d',
    storageBucket: 'notes-flutter-8b72d.firebasestorage.app',
    androidClientId: '696167834323-ic958u8nn2ki8gp9kab7f0vs6l51jlq7.apps.googleusercontent.com',
    iosClientId: '696167834323-c7ljbbi7eaa3met78hchqqpo11d5pkcg.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo4dtpH3fxsjLV7TonfSnxAzhBErZilgY',
    appId: '1:696167834323:ios:31c3f2758ba2c88b44aa26',
    messagingSenderId: '696167834323',
    projectId: 'notes-flutter-8b72d',
    storageBucket: 'notes-flutter-8b72d.firebasestorage.app',
    androidClientId: '696167834323-ic958u8nn2ki8gp9kab7f0vs6l51jlq7.apps.googleusercontent.com',
    iosClientId: '696167834323-c7ljbbi7eaa3met78hchqqpo11d5pkcg.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFlutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0E9hLYvjvadXMDnqY6HexGZuQITzr0A4',
    appId: '1:696167834323:web:c19d259fbbe98e7444aa26',
    messagingSenderId: '696167834323',
    projectId: 'notes-flutter-8b72d',
    authDomain: 'notes-flutter-8b72d.firebaseapp.com',
    storageBucket: 'notes-flutter-8b72d.firebasestorage.app',
    measurementId: 'G-TKEEWTFMQ4',
  );

}